version: '3.3'

services:
  ihr-webapp-db:
    image: 'ihr-webapp-db'
    build: 
      context: ./
      dockerfile: ihr-webappdb-docker
    ports:
      - '27017:27017'

  ihr-webapp:
    image: ihr-webapp
    build: 
      context: ./
      dockerfile: ihr-webapp-docker
    environment:
      NODE_ENV: "docker"
    ports:
      - 3000:3000
    depends_on: 
      - ihr-webapp-db
    volumes:
    - './ihr-webapp:/usr/local/app'