version: '3.3'

services:
  mongodb:
    image: 'ihr-webapp-db'
    build: './ihr-webappdb-docker'
    hostname: ihr-webapp-db
    container_name: ihr_web_app_db
    expose:
      - '27017'
    volumes:
      - ./database:/data/db

  ihr-webapp:
    image: ihr-webapp
    build: './ihr-webapp-docker'
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on: 
      - mongodb
    volumes:
    - './ihr-webapp:/usr/local/app'