version: '3.3'

services:
  mongodb:
    image: 'mongo'
    hostname: ihr-webapp-db
    container_name: ihr_web_app_db
    ports:
      - '27017:27017'
    volumes:
      - ./database:/data

  ihr-webapp:
    image: ihr-webapp
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on: 
      - mongodb
    volumes:
    - './ihr-webapp:/usr/src/app'